### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by wulfric93** [Shellgate/tcp_optimization_bbr#2]
As You see there is problem on Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-89-generic aarch64)
<img width="344" alt="image" src="https://github.com/Shellgate/tcp_optimization_pcc/assets/117269334/a753a3ee-d8c9-4fa3-aa17-5fe85b1342e9">

**Comment by Shellgate** [comment]
My suggestion is to replace the file with the code itself If you enter the codes manually, it will be difficult to set To fully use all the features, your kernel and operating system must be up to date It is recommended from 
```shell

do-release-upgrade

``` 

can be used and the suggested kernel for you Xanmod-kernel It provides all facilities for you

```shell

wget -qO - https://dl.xanmod.org/archive.key | sudo gpg --dearmor -o /usr/share/keyrings/xanmod-archive-keyring.gpg

``` 

```shell

echo 'deb [signed-by=/usr/share/keyrings/xanmod-archive-keyring.gpg] http://deb.xanmod.org releases main' | sudo tee /etc/apt/sources.list.d/xanmod-release.list

``` 

at the end of apt update you use and install the kernel version suitable for your processor and generation 

for example 

```shell
apt reinstall linux-xanmod-x64v1
```
